### ISSUE TITLE
auto voicechannel not working with private posse's 

### ISSUE THREAD

**Issue by chriswortman** [TPBubbleU/DeadwoodObituary#1]
After trying to create a private posse with just a few people, the bot no longer creates a new voice channel when joining 'round up a posse'.   I tried removing everyone from the posse, and still no new voice channel. 

![image](https://user-images.githubusercontent.com/10570696/211666594-380cf29c-7ab2-40f6-add6-7ab516de18f4.png)
![image](https://user-images.githubusercontent.com/10570696/211666568-cf56cf2e-2791-4271-87a8-ebf2915c2dee.png)

**Comment by chriswortman** [comment]
Was able to get it setup on my test server, skipped the spotify stuff, but am able to re-pro the issue. 

```
Started the process of deleting a channel at 2023-01-10 22:23:19.073666
Started the process of making a new channel at 2023-01-10 22:23:20.564669
Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "//Bot.py", line 176, in on_voice_state_update
    newChannel = await guild.create_voice_channel(name=channelName, bitrate=96000, category=categoryChannel, overwrites=overwrites)
  File "/usr/local/lib/python3.9/dist-packages/discord/guild.py", line 1247, in create_voice_channel
    data = await self._create_channel(
  File "/usr/local/lib/python3.9/dist-packages/discord/guild.py", line 1043, in _create_channel
    payload = {'allow': allow.value, 'deny': deny.value, 'id': target.id}
AttributeError: 'NoneType' object has no attribute 'id'
```
